### ISSUE TITLE
config file missing from conda distribution

### ISSUE THREAD

**Issue by DCrouse** [tesera/pygypsy#58]
The characters after the main command are just to direct output from the console to a text file, and don't have any impact on the python command since I also tried it without the redirect initially.  Also tried this on both Carol Ann and my machines and had the same error

[output_generate_config.txt](https://github.com/tesera/pygypsy/files/652206/output_generate_config.txt)

**Comment by jo-tham** [comment]
thx dwight! will look at this and release a new version today
