### ISSUE TITLE
pygypsy does not do dataprep on windows

### ISSUE THREAD

**Issue by DCrouse** [tesera/pygypsy#59]
The characters after the main command are just to direct output from the console to a text file, and don't have any impact on the python command since I also tried it without the redirect initially.  Also tried this on both Carol Ann and my machines and had the same error

[output_prep.txt](https://github.com/tesera/pygypsy/files/652215/output_prep.txt)

**Comment by jo-tham** [comment]
This has the same root cause as #58. Progress/further comments will be tracked in #58. Closing this one.
