### ISSUE TITLE
fieldname for stand_id is still not transferred to the prepped output table

### ISSUE THREAD

**Issue by DCrouse** [tesera/pygypsy#64]
![image](https://cloud.githubusercontent.com/assets/1724094/21274725/e065e538-c386-11e6-9495-dfc915f683bd.png)

**Comment by jo-tham** [comment]
can you copy the whole header and paste it here?

I think it might be there just not in first column

**Comment by jo-tham** [comment]
for record:

,BA_Aw,BA_Pl,BA_Sb,BA_Sw,BAinc_Aw,BAinc_Pl,BAinc_Sb,BAinc_Sw,N0_Aw,N0_Pl,N0_Sb,N0_Sw,N_Aw,N_Pl,N_Sb,N_Sw,SDF_Aw,SDF_Pl,SDF_Sb,SDF_Sw,SI_Aw,SI_Pl,SI_Sb,SI_Sw,StumpDOB_Aw,StumpDOB_Pl,StumpDOB_Sb,StumpDOB_Sw,StumpHeight_Aw,StumpHeight_Pl,StumpHeight_Sb,Stumpheight_Sw,TopDib_Aw,TopDib_Pl,TopDib_Sb,TopDib_Sw**,id_l1,**tage_Aw,tage_Pl,tage_Sb,tage_Sw,topHeight_Aw,topHeight_Pl,topHeight_Sb,topHeight_Sw,y2bh_Aw,y2bh_Pl,y2bh_Sb,y2bh_Sw

best option is to remove the duplicate index column that has no header

ordering of columns is up for discussion. provides some convenience to human readers but at this stage not worth introducing the complexity. no benefit for client applicaitons

glad to hear other thoughts

**Comment by jo-tham** [comment]
there is a simple solution for getting the plot id first

write the index column and specify a name for it

i will make this change
