### ISSUE TITLE
high res simulation produces too many curves for forest estate modelers and their audiences

### ISSUE THREAD

**Issue by jo-tham** [tesera/pygypsy#75]
we need to aggregate the output curves, or aggregate the input data

**Comment by ianmoss** [comment]
The title of this is misleading.  It is not too many curves for forest models - it is too many curves for modellers and those who wish to interpret the data.

**Comment by jo-tham** [comment]
@ianmoss please edit the title as you see fit 

<img width="898" alt="screen shot 2017-01-18 at 11 33 13 am" src="https://cloud.githubusercontent.com/assets/7353689/22079798/ec5c2366-dd71-11e6-97ce-3c5f898a249b.png">

let me know if that edit button on the right is not available for you

**Comment by jo-tham** [comment]
discussed today - agreed that this is out of scope of pygypsy.

time series aggregation is a tool to itself (e.g. to use iwth other G&Y models, or other types of time series data) or the aggregation is done on the input data
