### ISSUE TITLE
Data prep hangs

### ISSUE THREAD

**Issue by CarolCrouse** [tesera/pygypsy#80]
It looks like the 10,000 data set has timed out on my machine.  It's been stuck at 70% complete since last night and no outputs have been made.  It looks like it's trying to calculate to an age of -1 and might be stuck on that because the message says "Slow Convergence".  

Talking with Dwight it shouldn't be calculating age and this is implying that it is instead of using age from the data.  Anyway I expect this is the same issue as the ages >1000, which has to be ironed out as Ian commented in #79

![image](https://cloud.githubusercontent.com/assets/7502509/22068038/e9639b38-dd50-11e6-9eae-b11c1d73da03.png)

**Comment by jo-tham** [comment]
@CarolCrouse can you upload the log files?

**Comment by CarolCrouse** [comment]
@jo-tham there's nothing in them.  I was only on the prep portion when it stalled.

[prep.txt](https://github.com/tesera/pygypsy/files/714456/prep.txt)

**Comment by jo-tham** [comment]
closing, same underlying problem as #79
