### ISSUE TITLE
Discret year column for the inventory update

### ISSUE THREAD

**Issue by juliannosambatti** [tesera/pygypsy#81]
We will need to to the inventory update according to discrete years (e.g. 2014, 2015 etc until invetory updated age )

cc @jo-tham

**Comment by jo-tham** [comment]
@juliannosambatti can you elaborate on this? maybe some example of how the output data should look?

is it the same as #65?

**Comment by juliannosambatti** [comment]
[Example output.csv.zip](https://github.com/tesera/pygypsy/files/725291/Example.output.csv.zip)

**Comment by jo-tham** [comment]
Thanks

Do you have an approach in mind to implement this?

**Comment by juliannosambatti** [comment]
@jo-tham, could you please do a quick test on the code I commited for this issue? #81/Discrete_year.
