### ISSUE TITLE
revise unreasonable site index/tree height/age given the other two or skip young plots in data prep

### ISSUE THREAD

**Issue by jo-tham** [tesera/pygypsy#83]
## User story

```
As a user
I want unreasonable input data (such as site index of 0) to be set to reasonable values
So that every plot gets a projection
```
## Actual solution

-  a separate schema

## Implementation

Given 1 unreasonable (0, negative, etc) values in these 3 variables:

- site index
- tree height
- age 

we can solve for the missing one. Note that this also applies to missing, not just unreasonable, data. This could be config.

## Questions:

- what % of plots does this affect
- raw data (input to prep) vs prepped data (input to simulation)
- should these checks be on raw data, at end of prep, and start of simulation?

## Things to differentiate:

- missing data, erroneous data
- data erroneous because of intermediate calculations or as raw input

--------------------------------------
Other points of discussion

This user story, can be handled with #76 

```
As a user
I want the system to record and skip plots with incomplete data (null)
So that errors aren't raised / processing continues
So that I can revise the data
```

```
As a user
I want the raw and prepped data to be QA/QC'd
So that pygypsy doesn't crash with bad data
```

**Comment by jo-tham** [comment]
@DCrouse @juliannosambatti @ianmoss 

here's some summaries of the (SLS) data that may help us decide how to approach problematic input values to pygypsy. Maybe you can discern whether some of these should even have gypsy run on them

# Raw summary of the data
[summary.csv.zip](https://github.com/tesera/pygypsy/files/731070/summary.csv.zip)

![boxplots](https://cloud.githubusercontent.com/assets/7353689/22311595/02fcdef2-e309-11e6-99c9-db03f8870ee8.png)
# Boxplots

i suggest, for now, we simply implement #76 and record failed plots. I think the percent of failed plots is quite low. 

Lets continue testing and gather more data about which plot characteristics fail. We can then look more systematically into handling plots with valid but problematic (for gypsy) data.

Plots with invalid data should simply be skipped for simplicity, for now. In general, these problems should be caught elsewhere (such as with a database schema)

**Comment by jo-tham** [comment]
@juliannosambatti asked about the boxplots

I used juptyer notebook

Here's the pdf

[data-summary.html.zip](https://github.com/tesera/pygypsy/files/731086/data-summary.html.zip)

if you have jupyter notebook you can work from my raw notebook
[notebook.ipynb.zip](https://github.com/tesera/pygypsy/files/731092/notebook.ipynb.zip)

install and run jupyter notebook like so:

```
cd ~/projects/data-check
virtualenv venv
. venv/bin/activate
pip install matplotlib pandas jupyter
jupyter notebook
```

**Comment by DCrouse** [comment]
within the 1million record dataset this site index issue impacts 11 records amount to 1,2 hectares.  Looking at these visually, these are all small forested "openings" (classed VF in LCC)) with a leading species of pine assigned with low lorey's mean tree heights, less than 1.3 meters and ages less than 16.  There is a pine site index generated but it wasn't populated in the SI column.  I'm guessing the heights/ages were too low for a site index to be produced.

In terms of a resolution, there will not be any volumes assigned to these stands from GYPSY since they are too young so I think the resolution is to just skip them in the processing and we can report the records that were not processed via an an output file which has the information for the entire record and we move on.  Fair?

**Comment by jo-tham** [comment]
@juliannosambatti @ianmoss @DCrouse @CarolCrouse 

here's the proportion of plots from the 1.3 million microstands which could be problematic

1.2% of plots with predicted land cover class of VF (or VF_<something>)

<img width="1099" alt="screen shot 2017-01-25 at 2 59 21 pm" src="https://cloud.githubusercontent.com/assets/7353689/22312927/f5e95d98-e30e-11e6-9075-e395e1ddc0a7.png">

we can play around with the heuristic (`HEIGHT < 1.3 or AGE <= 25 or SI <=0 or BHAGE < 0`). I can send you the jupyter notebook if you want to play around with it further

@DCrouse @CarolCrouse are those the plots you want to target when reviewing in GIS?

**Comment by jo-tham** [comment]
> @juliannosambatti @jo-tham
> 
> within the 1million record dataset this site index issue impacts 11 records amount to 1,2 hectares. Looking at these visually, these are all small forested "openings" (classed VF in LCC)) with a leading species of pine assigned with low lorey's mean tree heights, less than 1.3 meters and ages less than 16. There is a pine site index generated but it wasn't populated in the SI column. I'm guessing the heights/ages were too low for a site index to be produced.
> 
> In terms of a resolution, there will not be any volumes assigned to these stands from GYPSY since they are too young so I think the resolution is to just skip them in the processing and we can report the records that were not processed via an an output file which has the information for the entire record and we move on. Fair? cc: @ianmoss

awesome, thanks @DCrouse 

@juliannosambatti i think we can resolve this by skipping young plots in data prep (we already do this in the simulation)
