### ISSUE TITLE
Missing Curves - make it clearer to users which plots are skipped

### ISSUE THREAD

**Issue by CarolCrouse** [tesera/pygypsy#92]
@juliannosambatti @jo-tham 
I've completed running Gypsy using the 1000 and 10,000 test sets.  They are now running with no errors or messages appearing.  However when I check the count of curves created from the 10,000 data set I noticed that Gypsy is only producing 9994 unique curve files from the 10,000 that are listed in the input test dataset.  The curves id's that are not being produced are 9573, 9600, 9630,9631, 9728 and 9729.  I'm not sure why this is or if it's related to the age fix you implemented.  Let me know a location and I can post all the data for you to review this issue and also review that the individual curve files are producing the correct results.
FYI:  The 10,000 dataset only took 5 minutes to run locally and the 100,000 is currently running and I expect it to complete in about an hour.

**Comment by jo-tham** [comment]
thanks @CarolCrouse!

as for the missing plots, can you just post the log file from the 10 000 run?

in the future we can get the log message in the terminal to indicate that plots are being skipped, instead of just burying it in the log file :)

**Comment by CarolCrouse** [comment]
@jo-tham 
I assume it's the prep log file you want since the plots are missing in the prepped csv file. 
[prep.txt](https://github.com/tesera/pygypsy/files/743329/prep.txt)

FYI. The 100,000 test set just finished in 1 hour 10 minutes. It is missing 33 curves.

**Comment by CarolCrouse** [comment]
FYI.  The 100,000 test set just finished in 1 hour 10 minutes.  It is missing 33 curves.

**Comment by jo-tham** [comment]
good assumption :)

here's the pertinent messages; it is indeed skipping plots with a low age and it is the 6 you mentioned

```
> grep -r -i 'error' prep.txt
...ERROR 2017-01-31 13:50:02,276 Dominant species age is less than minimum age 25;skipping plot 9573
... ERROR 2017-01-31 13:50:02,380 Dominant species age is less than minimum age 25;skipping plot 9600
... ERROR 2017-01-31 13:50:02,493 Dominant species age is less than minimum age 25;skipping plot 9630
... ERROR 2017-01-31 13:50:02,493 Dominant species age is less than minimum age 25;skipping plot 9631
... ERROR 2017-01-31 13:50:02,831 Dominant species age is less than minimum age 25;skipping plot 9728
... ERROR 2017-01-31 13:50:02,831 Dominant species age is less than minimum age 25;skipping plot 9729
```

does that answer your  question about the missing plots @CarolCrouse? would you like to see any changes?

**Comment by CarolCrouse** [comment]
@jo-tham @juliannosambatti I checked the data and it's skipping microstands where age <25.  This needs to be reviewed with Ian I think.

**Comment by jo-tham** [comment]
@CarolCrouse this stems from #27 and #83 

we've had some discussion with @ianmoss but, to cover the possibilities, the minimum age is an option in the configuration file:

https://github.com/tesera/pygypsy/blob/dev/pygypsy/scripts/config/default-conf.json#L2

so, it can be adjusted to whatever value is deemed appropriate in each case

that said, if the missing plots from the prepped data and simulation are explained and if there's nothing else that needs to change based on this issue, I will close it

**Comment by jo-tham** [comment]
@CarolCrouse @DCrouse as for the list of skipped plots; im hesitant to change this in the code because the list is available in `prep.log`

from your perspective, is it OK to use the find function in text editor to find places with 'ERROR' or 'skipped' in the log file to identify the ids of skipped plots?

**Comment by jo-tham** [comment]
if not i have a good approach in mind, but it will have to wait a few weeks

**Comment by jo-tham** [comment]
closing since this is available in log - can be reopened if there's clearer user need to isolate the skipped plots
